//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.fruit.org")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.fruit.org", IsNullable=false)]
public partial class fruits {
    
    private fruitsFruit[] fruitField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("fruit")]
    public fruitsFruit[] fruit {
        get {
            return this.fruitField;
        }
        set {
            this.fruitField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.fruit.org")]
public partial class fruitsFruit {
    
    private string nameField;
    
    private string shapeField;
    
    private fruitsFruitHarvestseason harvestseasonField;
    
    private string familyField;
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string shape {
        get {
            return this.shapeField;
        }
        set {
            this.shapeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("harvest-season")]
    public fruitsFruitHarvestseason harvestseason {
        get {
            return this.harvestseasonField;
        }
        set {
            this.harvestseasonField = value;
        }
    }
    
    /// <remarks/>
    public string family {
        get {
            return this.familyField;
        }
        set {
            this.familyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.fruit.org")]
public enum fruitsFruitHarvestseason {
    
    /// <remarks/>
    Spring,
    
    /// <remarks/>
    Summer,
    
    /// <remarks/>
    Fall,
    
    /// <remarks/>
    Winter,
}
